# Generated by Django 3.1.2 on 2021-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('short_descriptions', models.TextField()),
                ('descriptions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(db_index=True, max_length=150)),
                ('good_answer', models.CharField(db_index=True, max_length=150)),
                ('first_answer', models.CharField(db_index=True, max_length=150)),
                ('second_answer', models.CharField(db_index=True, max_length=150)),
                ('third_answer', models.CharField(db_index=True, max_length=150)),
                ('fourth_answer', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
