# Generated by Django 3.1.2 on 2021-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(db_index=True, max_length=250)),
                ('answer', models.CharField(db_index=True, max_length=650)),
            ],
        ),
    ]
