# Generated by Django 3.1.2 on 2021-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='media/img_point/%Y/%m%d'),
            preserve_default=False,
        ),
    ]
