# Generated by Django 3.1.2 on 2021-03-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
