# Generated by Django 3.1.2 on 2021-04-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
