# Generated by Django 3.1.2 on 2021-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210407_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsored',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('www', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/sponsored/%Y/%m%d')),
            ],
        ),
    ]
