# Generated by Django 3.1.2 on 2021-03-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.answers'),
            preserve_default=False,
        ),
    ]
