# Generated by Django 3.1.2 on 2021-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210326_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='first_answer',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='fourth_answer',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='second_answer',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='third_answer',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
